# Generated by Django 4.1.6 on 2023-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabhunt', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
