# Generated by Django 4.1.6 on 2023-02-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollabhunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
