# Generated by Django 4.1.6 on 2023-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabhunt', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'kollabhunt_tags',
                'managed': True,
            },
        ),
    ]
