# Generated by Django 4.1.6 on 2023-03-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kollabhunt', '0006_project_projecttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='KollabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kollab_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kollabhunt_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KollabProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=600, unique=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kollabhunt.tag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tag', to='kollabhunt.kollabprofile')),
            ],
            options={
                'db_table': 'kollabhunt_profile_tags',
                'managed': True,
            },
        ),
    ]
